### ISSUE TITLE
Make DN icon retina friendly!

### ISSUE THREAD

**Issue by clintonhalpin** [pauldessert/Designer-News-Share-Button#3]
![screen shot 2015-01-08 at 8 03 23 am](https://cloud.githubusercontent.com/assets/523933/5662884/e5af0662-970c-11e4-8ea9-0d05cc12ebc3.png)

Maybe you could use a SVG?

EDIT: looks like its just the readme

**Comment by pauldessert** [comment]
Yup. The Readme is a JPG, the JS file contains CSS and a base64 encoded DN logo. I believe it will scale for Retina since the logo natural size is 60px X 60px.
